---
- name: Docker host configuration
  remote_user: root
  become: yes
  hosts: all
  vars:
    corr_path: "/etc/corrections/corr"
    time: "{{ lookup('pipe', 'date -d \"1 day ago\" +\"%Y%m%d\"') }}"
  tasks:
    - name: run the correction
      shell: "{{ corr_path }}{{ name }} >> /tmp/corr-{{ inventory_hostname }}-{{ name }}-{{ time }}"
    - name: copy file from remote server
      fetch:
              src: /tmp/corr-{{ inventory_hostname }}-{{ name }}-{{ time }}
              dest: /etc/cli/correction-result/corr-{{ inventory_hostname }}-{{ name }}-{{ time }}
              mode: 0774
              flat: yes
