- name: Docker host configuration
  hosts: all
  remote_user: root
  become: yes
  vars:
    time: "{{ lookup('pipe', 'date -d \"1 day ago\" +\"%Y%m%d\"') }}"
  tasks:
    - name: getting docker version
      shell: 'docker version | grep  Engine -A 1 | sed -n 2p | cut -d " " -f 13 > /tmp/version-{{ inventory_hostname }}-{{ time }}'
    - name: getting runc version
      shell: 'runc -v | grep runc | cut -d " " -f 3 >> /tmp/version-{{ inventory_hostname }}-{{ time }}'
    - name: getting containerd version
      shell: 'docker version | grep  containerd -A 1 | sed -n 2p | cut -d " " -f 13 >> /tmp/version-{{ inventory_hostname }}-{{ time }}'
    - name: copy file from remote server
      fetch:
              src: /tmp/version-{{ inventory_hostname }}-{{ time }}
              dest: /etc/cli/version/
              mode: 0774
              flat: yes
